### ISSUE TITLE
fs-loader gives error: `NodeInvocationException: n.i(...) is not a function`

### ISSUE THREAD

**Issue by ghost** [fulls1z3/ngx-config#31]
I'm using Angular 4 Universal with .net core 2 (vs 2017 core 2 template)
I have installed:
  "@ngx-config/core": "^0.2.0-rc.5",
    "@ngx-config/fs-loader": "^0.2.0-beta.1",

my setup:
`export function configFactory(): ConfigLoader {
  return new ConfigFsLoader('./ng-app-settings.json'); // FILE PATH
}
  imports: [

    ConfigModule.forRoot({
      provide: ConfigLoader,
      useFactory: (configFactory)
    }),
`
and I get an error at run time:

> NodeInvocationException: n.i(...) is not a function
TypeError: n.i(...) is not a function
at t.loadSettings (\ClientApp\dist\main-server.js:18307:931)
at t.init (C:\projects\stash\liveflo\liveflo.spa\src\XpertHR.Liveflo.SPA\ClientApp\dist\main-server.js:11120:1234)

my package.json

`{
  "name": "xperthrliveflospa",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/compiler-cli": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/platform-browser-dynamic": "4.2.5",
    "@angular/platform-server": "4.2.5",
    "@angular/router": "4.2.5",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.4",
    "@ngrx/store": "^2.2.3",
    "@ngrx/store-devtools": "^3.2.4",
    "@ngtools/webpack": "1.5.0",
    "@ngx-config/core": "^0.2.0-rc.5",
    "@ngx-config/fs-loader": "^0.2.0-beta.1",
    "@ngx-config/http-loader": "^0.2.0-rc.1",
    "@types/webpack-env": "1.13.0",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "file-loader": "0.11.2",
    "file-system": "^2.2.2",
    "html-loader": "0.4.5",
    "intl": "^1.2.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "typescript": "2.4.1",
    "url-loader": "0.5.9",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "@types/jquery": "^3.2.11",
    "@types/node": "~6.0.60",
    "@types/yfiles": "0.0.2",
    "chai": "4.0.2",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3",
    "ngrx-store-freeze": "^0.1.9",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "webpack": "^2.5.1"
  }
}`

**Comment by fulls1z3** [comment]
@shivark I assume you have this error message either on a production build, or the output code has been uglified/minified. This way, I have really very little information about what exactly you're facing there.

Could you please turn them off and observe the debug message, for a better chance to reproduce this?

**Comment by ghost** [comment]
Hi thanks for the reply. I couldn't turn off the uglify, but found where it fails:

` ConfigFsLoader.prototype.loadSettings = function () {
        return Promise.resolve(JSON.parse(readFileSync(this.path, 'utf8')))
            .then(function (settings) { return settings; })
            .catch(function () { return Promise.reject('Path unreachable!'); });
    };`
readFileSync is not defined. 

So in config.fs-loader.js  `import { readFileSync } from 'fs';` does not work. 

Do you know why? Do I need a specific Node version? or is it dependent on other npm?

My current node version: v6.11.0

**Comment by fulls1z3** [comment]
@shivark thanks for debugging it line-by-line, and now things are obvious.

Actually `fs` belongs to the server part of Node.js environment - not the browser. However, within the **ngx-config** ecosystem, `fs-loader` only runs on a server environment. So here are my suggestions: 

- please check your *package.json*, and verify whether `@types/node` are included in your `devDependencies` or not
- also, check your *tsconfig.json* and whether if you use all **types** (*if any *types* are declared, then the compiler use them - if not, uses all*)
- again in your *tsconfig.json*, check if *typeRoots* exists - which defaults to `node_modules/@types`
- again in your *tsconfig.json*, check *include*, *exclude* and *files* sections about inclusion of that erroneous file to the compilation

Beyond this point, you've gotta check your build tool (*systemjs, webpack, fuse-box, rollup, etc*). Basically this failure happens when mocking the `fs` at the browser environment and each has a different method to mock the `fs`.

For webpack, you can check this config (https://github.com/ng-seed/angular-webpack-config/blob/master/src/webpack.common.js#L447) at  [angular-webpack-config](https://github.com/ng-seed/angular-webpack-config) repo.

Let me know about the results, and happy coding!
